### ISSUE TITLE
Hi, i wonder how to use trained model to test accuracy or to classify my images.

### ISSUE THREAD

**Issue by qkyo** [wkcn/AttentionSampler#5]
Hi, i wonder how to use trained model to test accuracy or to classify my images. The original author seems to too busy to take care of his github. if you have done any work related it, plz give me some guidance. thank u so much

**Comment by qkyo** [comment]
it seems like there are no test file in this project, or maybe i ignore it. Thanks again!

**Comment by qkyo** [comment]
btw, sth seems to be wrong. I have added your files, 

Error in CustomOp.forward: Traceback (most recent call last):
  File "E:\Anaconda3\envs\python37\lib\site-packages\mxnet-1.3.1-py3.7.egg\mxnet\operator.py", line 987, in forward_entry
    aux=tensors[4])
  File "E:\Anaconda3\envs\python37\lib\site-packages\mobulaop-2.32-py3.7.egg\mobula\glue\mx.py", line 103, in forward
    out = self._forward(*in_data)
  File "./AttentionSampler/attention_sampler\attention_sampler.py", line 45, in forward
    attxi = F.cumsum(attx, 1)
AttributeError: module 'mxnet.ndarray' has no attribute 'cumsum'

this problem arises.I wonder if this is a problem with the mxnet version,

**Comment by vb123er951** [comment]
Hi @qkyo , the author has update the code to support old version of mxnet, maybe you can try again.

Also I'm wondering how to do testing in TASN by only use master-net... @wkcn can you give some suggestions?

**Comment by wkcn** [comment]
Hi @vb123er951 , I am not familiar with it.

You can ask the author @Heliang-Zheng.
